name: Hello Action
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-cpp
        run: |
          apt install build-essential
      - name: checkout
        uses: actions/checkout@master
      - name: build cpp
        run:  sh build.sh