name: Hello Action
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-cpp
        run: |
          sudo apt install build-essential cmake
      - name: checkout
        uses: actions/checkout@master
      - name: build cpp
        run:  |
          cmake -H. -Bbuild
          cmake --build build -- -j 4
      - name: execute program
        run: |
          cd build
          ./helloaction